 #install: conda env create -f environment.yaml
 #update:  conda env update -f environment.yaml

name: exploratree

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - yaml
  - ipython
